### PR TITLE
Use SECRET_KEY_BASE environment variable

### PR DESCRIPTION
**Pull request by basiszwo**
This is required for https://github.com/opf/openproject/pull/3583
where we align with rails basics.

### CODE REVIEW

**Comment by crohr** [comment]
Thanks for that, however the addon needs to be kept backwards compatible with older versions of OpenProject being packaged, hence you should add those lines without removing the old ones, so that both `SECRET_TOKEN` and `SECRET_KEY_BASE` get set.

**Comment by basiszwo** [comment]
@crohr updated the PR. ok like this?

**Comment by crohr** [comment]
@basiszwo I think you would need to reuse the existing `SECRET_TOKEN` if any, and set `SECRET_TOKEN` to the same value than `SECRET_KEY_BASE`:

```bash
# set SECRET_KEY_BASE env variable
secret_token=$(${CLI} config:get SECRET_KEY_BASE || ${CLI} config:get SECRET_TOKEN || ${CLI} run rake -s secret | tail -1)
${CLI} config:set SECRET_KEY_BASE="$secret_token"

# set SECRET_TOKEN env variable for backwards compatibility
${CLI} config:set SECRET_TOKEN="$secret_token"
```

**Comment by basiszwo** [comment]
Not sure about this. Either you have one set already and reuse it or you generate a new one. not?

**Comment by crohr** [comment]
That's actually what's happening: `secret_token` is set to whatever is returned by `SECRET_KEY_BASE` (upgrades from 5.x), or else `SECRET_TOKEN` (upgrades from 4.x), or finally falls back to generating a new token for new installs.

**Comment by basiszwo** [comment]
I aded your suggestion and squashed. I wantet to do it like this but went against it. sorry for extra works.

**Pull request merged**
